### ISSUE TITLE
Draft: First class dataset support

### ISSUE THREAD

**Issue by jmintb** [TeaInSpace/ame#120]
# Context

AME needs to provide features surrounding data sets. To facilitate this a dataset concept should be introduced allowing for user's of AME to think in terms of datasets instead of the more "low level" `Task` objects. 

This will allow for more advanced features specific to datasets.

# Design

An example of how the datasets should end up:

```yaml
dataSets:
    - name: good_data
      task: 
        taskRef: fetch_data

tasks:
    - name: training
      resources:
          cpu: 4
          memory: 8GB
          storage: 5GB
      command: python train.py
      dataSources:
        - name: good_data
        
    - name: fetch_data
      command: python refresh_data.py
      fromTemplate: common_templates.standard_data_fetch_template

```

# How to proceed

The initial implementation does not need to offer much functionality over a `Task`, dataset specific features can be implemented over time. Therefore for this issue we can think of Datasets as a wrapper around a `Task`

### Acceptance criteria

- [ ] There is a Dataset CRD
- [x] AME Projects can contain a list of datasets
- [x] `Tasks` can depend on a dataset, mean the dataset will be mounted inside the Task's directory.

### Open questions

- Does it make sense to reference datasets in the datasources field?
- How should datasets fetch data from outside sourcs such as s3?
