### ISSUE TITLE
Idea: Model servers

### ISSUE THREAD

**Issue by jmintb** [TeaInSpace/ame#161]
Just like we have executors for Tasks, we need something similar for deploying models. Right now AME is coupled to mlflow for serving models but that needs to change. This requires new options  in the AME files.

The proposed change:

```yaml
# main project ame.yml
project: xgboost_project
models:
  - name: product_recommendor
    training:
      task: 
        taskRef: train_my_model 
    deployment:
      server:
        !customer
        command: python serve.py
        pythonVersion: 3.11
        deps: pip

```
