### ISSUE TITLE
AME tasks and project configuration is stored in the project repository as yaml files

### ISSUE THREAD

**Issue by jmintb** [TeaInSpace/ame#36]
As an AME user I want to keep my task configuration saved so as to avoid repeatedly configuring how a task is executed. I also want this configuration to be under version control. Therefore I want to store the configuration in a yaml file within my project's repository.

Acceptance criteria:
1. All task configuration options are stored in an AME file within the root directory of the project.
2. Configuration options are saved when invoking the run command.
3. If no configuration file exists the user is asked if they wish to save the run options in the config file.
4. The CLI can create a configuration file and walk the user through relevant options.
5. The configuration file is always created with at least the options required to execute a task.
6. The local file should reflect the Task CRD spec along with projectID
7. The implementation can facilitate multiple tasks for a single project

Suggested file format:

```yaml
projectid: myproject
defaultTask: mytask
tasks:
- name: mytask
  command: python train.py
reacurringtasks:
- taskref: mytask
  crontab: ****20
  
```
